Repository vapor/fluent-kit, pull requests merged in 2019-12, with the labels that each got.

#102 beta.2
  .github/workflows/test.yml
  Package.swift
  README.md
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/GalaxySeed.swift
  Tests/FluentKitTests/XCTestManifests.swift
  Tests/LinuxMain.swift
Labels: enhancement

#104 Grouped SQL Filters
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/Trash.swift
  Sources/FluentSQL/SQLQueryConverter.swift
Labels: bug

#105 add array support
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentKit/Error.swift
  Sources/FluentKit/Model/Model.swift
  Sources/FluentKit/Model/SoftDeletable.swift
  Sources/FluentKit/Model/Timestampable.swift
  Sources/FluentKit/Properties/Field.swift
  Sources/FluentKit/Properties/OptionalParent.swift
  Sources/FluentKit/Properties/Property.swift
  Sources/FluentKit/Schema/DatabaseSchema.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
Labels: enhancement

#109 add eagerLoaded property to relations
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentKit/Properties/Children.swift
  Sources/FluentKit/Properties/Parent+EagerLoad.swift
  Sources/FluentKit/Properties/Property.swift
  Sources/FluentKit/Properties/Siblings.swift
Labels: enhancement

#111 [SomeCodable] stores as .array(of: .json) instead of .json
  Sources/FluentBenchmark/FluentBenchmarker.swift
Labels: enhancement

#113 Duplicate constraint name fix
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentKit/Model/Model.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: enhancement, semver-patch

#123 Don't eager load on empty result set
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentKit/Query/QueryBuilder.swift
Labels: bug, semver-patch

#124 Add UInt8-backed enum test
  Sources/FluentBenchmark/FluentBenchmarker.swift
Labels: bug, enhancement, semver-patch
