Repository vapor/fluent-kit, pull requests merged in 2020-08, with the labels that each got.

#362 Add raw query model decode helper
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/Tests/SQLTests.swift
  Sources/FluentSQL/SQLDatabase+Model.swift
Labels: enhancement, semver-minor

#368 Support disabling foreign key checks in benchmarker
  Sources/FluentBenchmark/Tests/SchemaTests.swift
Labels: enhancement, semver-patch

#380 Require value for @Parent when eager loaded
  Sources/FluentBenchmark/Tests/SoftDeleteTests.swift
  Sources/FluentKit/Properties/Parent.swift
  Sources/FluentKit/Query/Builder/QueryBuilder.swift
Labels: bug, semver-patch
