Repository vapor/fluent-kit, pull requests merged in 2020-10, with the labels that each got.

#398 Don't Re-Delete Soft-Deleted Models
  Sources/FluentBenchmark/Tests/SoftDeleteTests.swift
  Sources/FluentKit/Query/Builder/QueryBuilder.swift
Labels: bug, hacktoberfest-accepted, semver-patch

#391 Add eager loading for pivots on sibling relationships
  Sources/FluentBenchmark/Tests/SiblingsTests.swift
  Sources/FluentKit/Properties/Siblings.swift
Labels: enhancement, semver-minor

#399 Added Inline Documentation to ID Initializer
  Sources/FluentKit/Properties/ID.swift
Labels: hacktoberfest-accepted
