Repository vapor/fluent-kit, pull requests merged in 2020-11, with the labels that each got.

#401 Add Public Initializer to PageMetadata
  Sources/FluentKit/Query/Builder/QueryBuilder+Paginate.swift
Labels: bug, hacktoberfest-accepted, semver-patch

#400 More helpers for embedding raw SQL from the FluentKit layer
  Sources/FluentBenchmark/Tests/FilterTests.swift
  Sources/FluentBenchmark/Tests/RangeTests.swift
  Sources/FluentBenchmark/Tests/SchemaTests.swift
  Sources/FluentBenchmark/Tests/SortTests.swift
  Sources/FluentKit/Schema/SchemaBuilder.swift
  Sources/FluentSQL/DatabaseQuery+SQL.swift
  Sources/FluentSQL/DatabaseSchema+SQL.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
Labels: enhancement, semver-minor

#402 QueryBuilder needs a Field-taking `.field()` overload
  Sources/FluentKit/Query/Builder/QueryBuilder.swift
Labels: bug, enhancement, semver-minor

#387 Fix filtering on enum fields
  Sources/FluentBenchmark/Tests/FilterTests.swift
  Sources/FluentKit/Model/ModelAlias.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Filter.swift
Labels: semver-patch
