Repository vapor/fluent-kit, pull requests merged in 2020-07, with the labels that each got.

#328 Disallows private-scoped migrations with default names.
  Sources/FluentBenchmark/Tests/MigratorTests.swift
  Sources/FluentKit/Migration/Migration.swift
  Sources/FluentKit/Migration/Migrator.swift
Labels: bug, semver-patch

#342 Add missing join filter overload
  Sources/FluentKit/Query/Builder/QueryBuilder+Filter.swift
  Sources/XCTFluent/TestDatabase.swift
  Tests/FluentKitTests/QueryBuilderTests.swift
Labels: bug, enhancement, semver-minor

#322 add github action for automating api-docs
  .github/workflows/api-docs.yml
Labels: enhancement

#345 add Database.logging(to:) method
  Sources/FluentKit/Database/Database+Logging.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: enhancement, semver-minor

#349 Fix optional string contains operator
  Sources/FluentBenchmark/Tests/FilterTests.swift
  Sources/FluentSQL/SQLQueryConverter.swift
Labels: bug, semver-patch

#336 Add @Timestamp(key: "...", on: .none) functionality
  Sources/FluentBenchmark/Tests/TimestampTests.swift
  Sources/FluentKit/Properties/Timestamp.swift
Labels: enhancement, semver-minor

#351 Fix invalid @Enum value decode
  Sources/FluentKit/Enum/EnumProperty.swift
  Sources/FluentKit/Enum/OptionalEnumProperty.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: bug, semver-patch

#352 Allow generated @IDs to be overridden
  Sources/FluentKit/Model/Model+CRUD.swift
  Sources/FluentKit/Properties/ID.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: bug, semver-patch

#353 Fix @ID generation for nil values
  Sources/FluentBenchmark/Tests/IDTests.swift
  Sources/FluentKit/Properties/ID.swift
Labels: bug, semver-patch

#354 Add QueryBuilder.fields(for: Model)
  Sources/FluentKit/Query/Builder/QueryBuilder.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: enhancement, semver-minor

#356 Test benchmark updates
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/Tests/PerformanceTests+Siblings.swift
Labels: enhancement, semver-patch

#338 Add join methods for @Parent, @Children, and @Siblings
  Sources/FluentKit/Query/Builder/QueryBuilder+Join.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: enhancement, semver-minor

#360 Support @Enum usage in QueryBuilder.set
  Sources/FluentBenchmark/Tests/SetTests.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Set.swift
Labels: bug, semver-patch

#361 Simplify benchmark pooling + CI
  .github/workflows/test.yml
  Sources/FluentBenchmark/Tests/PerformanceTests+Siblings.swift
Labels: bug, semver-patch

#364 Add SQLConverterDelegate.beforeConvert method
  Sources/FluentBenchmark/Tests/SchemaTests.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
Labels: bug, enhancement, semver-minor
