Repository vapor/fluent-kit, pull requests merged in 2020-01, with the labels that each got.

#129 Added Model.hasChanges Property
  Sources/FluentKit/Model/Model.swift
Labels: enhancement, semver-minor

#130 Pagination and Range
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentKit/Query/QueryBuilder+Paginate.swift
  Sources/FluentKit/Query/QueryBuilder+Range.swift
  Sources/FluentKit/Query/QueryBuilder.swift
Labels: enhancement, semver-minor

#133 Fix ID.Generator.random Overwrite
  Sources/FluentBenchmark/Exports.swift
  Sources/FluentBenchmark/FluentBenchmarker+customID.swift
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentKit/Properties/ID.swift
Labels: bug

#135 SQLKit Updates
  Sources/FluentSQL/SQLSchemaConverter.swift
  Tests/FluentKitTests/DummyUtilities.swift
Labels: enhancement

#136 Fix join(_:on:) Typo
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentKit/Query/QueryBuilder.swift
Labels: bug, semver-patch

#137 Fix QueryBuilder.set(_:to:)
  Sources/FluentBenchmark/FluentBenchmarker+CustomID.swift
  Sources/FluentBenchmark/FluentBenchmarker+MultipleSet.swift
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentKit/Query/QueryBuilder.swift
Labels: bug
