Repository vapor/fluent-kit, pull requests merged in 2020-02, with the labels that each got.

#143 Add Relation Protocol + Load Method
  Sources/FluentBenchmark/FluentBenchmarker+RelationMethods.swift
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentKit/Error.swift
  Sources/FluentKit/Properties/Children.swift
  Sources/FluentKit/Properties/OptionalParent.swift
  Sources/FluentKit/Properties/Parent+EagerLoad.swift
  Sources/FluentKit/Properties/Parent.swift
  Sources/FluentKit/Properties/Property.swift
  Sources/FluentKit/Properties/Relation.swift
  Sources/FluentKit/Properties/Siblings.swift
Labels: enhancement, semver-major

#145 Add QueryBuilder.group for Grouping Filters
  Sources/FluentBenchmark/FluentBenchmarker+Group.swift
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentKit/Query/QueryBuilder+Group.swift
Labels: enhancement, semver-minor

#146 Rename !~~ Operator to !~
  Sources/FluentKit/Query/QueryBuilder.swift
Labels: enhancement, semver-patch

#140 Bind String Contains Operator Values
  Sources/FluentSQL/SQLQueryConverter.swift
Labels: bug, semver-minor

#153 Support dynamic ID key on create
  Sources/FluentBenchmark/FluentBenchmarker+ID.swift
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentKit/Model/Model+CRUD.swift
  Sources/FluentKit/Query/DatabaseQuery.swift
  Sources/FluentKit/Query/QueryBuilder.swift
Labels: enhancement, semver-minor

#151 Add isAttached and attachIfNeeded methods to Siblings
  Sources/FluentKit/Properties/Siblings.swift
Labels: enhancement, semver-minor

#156 Don't perform eager loads on aggregate queries
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentKit/Query/QueryBuilder.swift
Labels: bug

#141 Add isUnique to QueryBuilder
  Package.swift
  Sources/FluentKit/Query/DatabaseQuery.swift
  Sources/FluentKit/Query/QueryBuilder+Unique.swift
  Sources/FluentKit/Query/QueryBuilder.swift
  Sources/FluentSQL/SQLQueryConverter.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: enhancement, semver-minor

#160 Update to swift tools version 5.2
  .github/workflows/test.yml
  Package.swift
Labels: enhancement, semver-patch

#157 Include `name` in relation not loaded message
  Sources/FluentKit/Properties/Children.swift
  Sources/FluentKit/Properties/Parent.swift
  Sources/FluentKit/Properties/Siblings.swift
Labels: enhancement, semver-patch

#162 Move test models to UUID identifier
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/SolarSystem/Galaxy.swift
  Sources/FluentBenchmark/SolarSystem/Moon.swift
  Sources/FluentBenchmark/SolarSystem/Planet.swift
  Sources/FluentBenchmark/SolarSystem/PlanetTag.swift
  Sources/FluentBenchmark/SolarSystem/Star.swift
  Sources/FluentBenchmark/SolarSystem/Tag.swift
  Sources/FluentBenchmark/Tests/Array.swift
  Sources/FluentBenchmark/Tests/Children.swift
  Sources/FluentBenchmark/Tests/CustomID.swift
  Sources/FluentBenchmark/Tests/Enum.swift
  Sources/FluentBenchmark/Tests/ID.swift
  Sources/FluentBenchmark/Tests/Join.swift
  Sources/FluentBenchmark/Tests/Middleware.swift
  Sources/FluentBenchmark/Tests/Migrator.swift
  Sources/FluentBenchmark/Tests/Model.swift
  Sources/FluentBenchmark/Tests/MultipleSet.swift
  Sources/FluentBenchmark/Tests/NestedModel.swift
  Sources/FluentBenchmark/Tests/OptionalParent.swift
  Sources/FluentBenchmark/Tests/Performance.swift
  Sources/FluentBenchmark/Tests/SoftDelete.swift
  Sources/FluentBenchmark/Tests/Timestamp.swift
  Sources/FluentBenchmark/Tests/Unique.swift
  Sources/FluentBenchmark/Utilities/City.swift
  Sources/FluentBenchmark/Utilities/CitySeed.swift
  Sources/FluentBenchmark/Utilities/ErrorMigration.swift
  Sources/FluentBenchmark/Utilities/Match.swift
  Sources/FluentBenchmark/Utilities/School.swift
  Sources/FluentBenchmark/Utilities/SchoolSeed.swift
  Sources/FluentBenchmark/Utilities/Team.swift
  Sources/FluentBenchmark/Utilities/TeamMatchSeed.swift
  Sources/FluentBenchmark/Utilities/Trash.swift
  Sources/FluentBenchmark/Utilities/User.swift
Labels: enhancement, semver-patch

#164 Siblings eager load performance
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/Tests/SiblingsPerformance.swift
  Sources/FluentKit/Properties/Siblings.swift
  Sources/FluentKit/Query/DatabaseQuery.swift
Labels: enhancement, semver-patch

#165 add FieldKey type
  .github/workflows/test.yml
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/SolarSystem/Galaxy.swift
  Sources/FluentBenchmark/SolarSystem/Moon.swift
  Sources/FluentBenchmark/SolarSystem/Planet.swift
  Sources/FluentBenchmark/SolarSystem/PlanetTag.swift
  Sources/FluentBenchmark/SolarSystem/Star.swift
  Sources/FluentBenchmark/SolarSystem/Tag.swift
  Sources/FluentBenchmark/Tests/Array.swift
  Sources/FluentBenchmark/Tests/Children.swift
  Sources/FluentBenchmark/Tests/CustomID.swift
  Sources/FluentBenchmark/Tests/Enum.swift
  Sources/FluentBenchmark/Tests/ID.swift
  Sources/FluentBenchmark/Tests/Join.swift
  Sources/FluentBenchmark/Tests/Middleware.swift
  Sources/FluentBenchmark/Tests/Model.swift
  Sources/FluentBenchmark/Tests/MultipleSet.swift
  Sources/FluentBenchmark/Tests/NestedModel.swift
  Sources/FluentBenchmark/Tests/OptionalParent.swift
  Sources/FluentBenchmark/Tests/Performance.swift
  Sources/FluentBenchmark/Tests/SoftDelete.swift
  Sources/FluentBenchmark/Tests/Timestamp.swift
  Sources/FluentBenchmark/Tests/Unique.swift
  Sources/FluentKit/Database/DatabaseOutput.swift
  Sources/FluentKit/Database/DummyDatabase.swift
  Sources/FluentKit/Migration/MigrationLog.swift
  Sources/FluentKit/Model/AnyModel.swift
  Sources/FluentKit/Model/Model+CRUD.swift
  Sources/FluentKit/Model/Model.swift
  Sources/FluentKit/Operators/FieldOperators.swift
  Sources/FluentKit/Operators/ValueOperators.swift
  Sources/FluentKit/Properties/Children.swift
  Sources/FluentKit/Properties/Field.swift
  Sources/FluentKit/Properties/ID.swift
  Sources/FluentKit/Properties/OptionalParent.swift
  Sources/FluentKit/Properties/Parent.swift
  Sources/FluentKit/Properties/Timestamp.swift
  Sources/FluentKit/Query/DatabaseQuery.swift
  Sources/FluentKit/Query/QueryBuilder+Aggregate.swift
  Sources/FluentKit/Query/QueryBuilder+Filter.swift
  Sources/FluentKit/Query/QueryBuilder+Join.swift
  Sources/FluentKit/Query/QueryBuilder+Nested.swift
  Sources/FluentKit/Query/QueryBuilder+Set.swift
  Sources/FluentKit/Query/QueryBuilder+Sort.swift
  Sources/FluentKit/Query/QueryBuilder.swift
  Sources/FluentKit/Schema/DatabaseSchema.swift
  Sources/FluentKit/Schema/SchemaBuilder.swift
  Sources/FluentSQL/SQLQueryConverter.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: enhancement

#171 Refactor aggregates
  Sources/FluentKit/Query/DatabaseQuery.swift
  Sources/FluentKit/Query/QueryBuilder+Aggregate.swift
  Sources/FluentKit/Query/QueryBuilder.swift
  Sources/FluentSQL/SQLQueryConverter.swift
Labels: enhancement

#172 MigrationLog use UUID
  Sources/FluentBenchmark/Tests/Migrator.swift
  Sources/FluentKit/Migration/MigrationLog.swift
  Sources/FluentKit/Migration/Migrator.swift
Labels: enhancement

#174 refactor db config
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/Tests/Middleware.swift
  Sources/FluentKit/Database/Database.swift
  Sources/FluentKit/Database/Databases.swift
  Sources/FluentKit/Database/DummyDatabase.swift
Labels: enhancement

#176 add @CompoundField
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/Tests/CompoundField.swift
  Sources/FluentBenchmark/Tests/Join.swift
  Sources/FluentBenchmark/Tests/OptionalParent.swift
  Sources/FluentKit/Database/DatabaseOutput.swift
  Sources/FluentKit/Database/DummyDatabase.swift
  Sources/FluentKit/Migration/MigrationLog.swift
  Sources/FluentKit/Model/AnyModel+Codable.swift
  Sources/FluentKit/Model/AnyModel.swift
  Sources/FluentKit/Model/Model+CRUD.swift
  Sources/FluentKit/Model/Model.swift
  Sources/FluentKit/Operators/FieldOperators.swift
  Sources/FluentKit/Operators/ValueOperators.swift
  Sources/FluentKit/Properties/Children.swift
  Sources/FluentKit/Properties/CompoundField.swift
  Sources/FluentKit/Properties/Field.swift
  Sources/FluentKit/Properties/ID.swift
  Sources/FluentKit/Properties/OptionalParent.swift
  Sources/FluentKit/Properties/Parent.swift
  Sources/FluentKit/Properties/Property.swift
  Sources/FluentKit/Properties/Siblings.swift
  Sources/FluentKit/Properties/Timestamp.swift
  Sources/FluentKit/Query/QueryBuilder+Aggregate.swift
  Sources/FluentKit/Query/QueryBuilder+Sort.swift
  Sources/FluentKit/Query/QueryBuilder.swift
  Tests/FluentKitTests/DummyUtilities.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: enhancement

#175 Reinitialize Driver
  Sources/FluentKit/Database/Databases.swift
Labels: enhancement

#178 add @Enum
  .github/workflows/test.yml
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/SolarSystem/Moon.swift
  Sources/FluentBenchmark/SolarSystem/Planet.swift
  Sources/FluentBenchmark/SolarSystem/Star.swift
  Sources/FluentBenchmark/Tests/AggregateTests.swift
  Sources/FluentBenchmark/Tests/ArrayTests.swift
  Sources/FluentBenchmark/Tests/BatchTests.swift
  Sources/FluentBenchmark/Tests/CRUDTests.swift
  Sources/FluentBenchmark/Tests/ChildrenTests.swift
  Sources/FluentBenchmark/Tests/ChunkTests.swift
  Sources/FluentBenchmark/Tests/CustomIDTests.swift
  Sources/FluentBenchmark/Tests/EagerLoadTests.swift
  Sources/FluentBenchmark/Tests/EnumTests.swift
  Sources/FluentBenchmark/Tests/FilterTests.swift
  Sources/FluentBenchmark/Tests/IDTests.swift
  Sources/FluentBenchmark/Tests/JoinTests.swift
  Sources/FluentBenchmark/Tests/MiddlewareTests.swift
  Sources/FluentBenchmark/Tests/MigratorTests.swift
  Sources/FluentBenchmark/Tests/ModelTests.swift
  Sources/FluentBenchmark/Tests/ParentTests.swift
  Sources/FluentBenchmark/Tests/PerformanceTests+Siblings.swift
  Sources/FluentBenchmark/Tests/PerformanceTests.swift
  Sources/FluentBenchmark/Tests/RelationTests.swift
  Sources/FluentBenchmark/Tests/SetTests.swift
  Sources/FluentBenchmark/Tests/SiblingsTests.swift
  Sources/FluentBenchmark/Tests/SoftDeleteTests.swift
  Sources/FluentBenchmark/Tests/TimestampTests.swift
  Sources/FluentBenchmark/Tests/UniqueTests.swift
  Sources/FluentKit/Database/Database.swift
  Sources/FluentKit/Database/DummyDatabase.swift
  Sources/FluentKit/Enum/DatabaseEnum.swift
  Sources/FluentKit/Enum/EnumBuilder.swift
  Sources/FluentKit/Enum/EnumMetadata.swift
  Sources/FluentKit/Enum/EnumProperty.swift
  Sources/FluentKit/Migration/MigrationLog.swift
  Sources/FluentKit/Model/Model+CRUD.swift
  Sources/FluentKit/Properties/Field.swift
  Sources/FluentKit/Properties/ID.swift
  Sources/FluentKit/Query/DatabaseQuery.swift
  Sources/FluentKit/Query/QueryBuilder.swift
  Sources/FluentKit/Schema/DatabaseSchema.swift
  Sources/FluentKit/Schema/SchemaBuilder.swift
  Sources/FluentSQL/SQLQueryConverter.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
  Tests/FluentKitTests/DummyUtilities.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: enhancement

#185 Cleanup DatabaseSchema foreign key
  .github/workflows/test.yml
  Sources/FluentKit/Properties/Children.swift
  Sources/FluentKit/Schema/DatabaseSchema.swift
  Sources/FluentKit/Schema/SchemaBuilder.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
Labels: bug, semver-minor

#186 QueryBuilder.fields helpers
  Sources/FluentBenchmark/Tests/CRUDTests.swift
  Sources/FluentKit/Model/Model+CRUD.swift
  Sources/FluentKit/Query/Builder/QueryBuilder.swift
Labels: enhancement, semver-minor
