Repository vapor/fluent-kit, pull requests merged in 2020-06, with the labels that each got.

#309 Require SQLKit 3.1.0
  Package.swift
Labels: bug, semver-patch

#311 Reduce query logging level
  Sources/FluentKit/Query/Builder/QueryBuilder.swift
Labels: enhancement, semver-patch

#312 Add query history
  Sources/FluentKit/Database/Database.swift
  Sources/FluentKit/Database/Databases.swift
  Sources/FluentKit/Query/Builder/QueryBuilder.swift
  Sources/FluentKit/Query/QueryHistory.swift
  Sources/XCTFluent/TestDatabase.swift
  Tests/FluentKitTests/QueryBuilderTests.swift
Labels: enhancement, semver-minor

#313 Fix @Timestamp decode from missing key
  Sources/FluentBenchmark/Tests/TimestampTests.swift
  Sources/FluentKit/Model/Fields+Codable.swift
  Sources/FluentKit/Properties/Timestamp.swift
Labels: bug, semver-patch

#320 Add input and output methods to Fields protocol
  Sources/FluentKit/Model/Fields.swift
Labels: enhancement, semver-minor

#314 Add `.dictionary` data type
  .github/workflows/test.yml
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/Tests/EagerLoadTests.swift
  Sources/FluentBenchmark/Tests/GroupTests.swift
  Sources/FluentBenchmark/Tests/JoinTests.swift
  Sources/FluentBenchmark/Tests/ParentTests.swift
  Sources/FluentBenchmark/Tests/PerformanceTests+Siblings.swift
  Sources/FluentKit/Properties/Property.swift
  Sources/FluentKit/Schema/DatabaseSchema.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
Labels: enhancement, semver-minor

#319 Fully qualified Migration names
  Sources/FluentBenchmark/Tests/MigratorTests.swift
  Sources/FluentKit/Migration/Migration.swift
  Sources/FluentKit/Migration/MigrationLog.swift
  Sources/FluentKit/Migration/Migrator.swift
Labels: bug, enhancement

#323 Fully qualified Migration names
  .github/workflows/test.yml
  Sources/FluentBenchmark/Tests/MigratorTests.swift
  Sources/FluentKit/Migration/Migration.swift
  Sources/FluentKit/Migration/Migrator.swift
Labels: enhancement, semver-minor

#305 Add optional string contains operators
  Sources/FluentBenchmark/Tests/FilterTests.swift
  Sources/FluentKit/Operators/ValueOperators+String.swift
  Sources/FluentKit/Utilities/OptionalType.swift
Labels: bug, semver-minor

#335 More CI fun
  .github/workflows/test.yml
Labels: enhancement

#337 Fix nil @Parent / @OptionalParent eager load
  Sources/FluentBenchmark/Tests/EagerLoadTests.swift
  Sources/FluentKit/Properties/OptionalParent.swift
  Sources/FluentKit/Properties/Parent.swift
Labels: bug, semver-patch

#340 Allow custom decimal type in tests
  .gitignore
  Sources/FluentBenchmark/Tests/PerformanceTests.swift
Labels: enhancement, semver-patch
