Repository vapor/fluent-kit, pull requests merged in 2020-04, with the labels that each got.

#228 Make @Timestamp encode as Date
  Sources/FluentKit/Properties/Timestamp.swift
Labels: bug, semver-patch

#232 Format Deleted Timestamp For Soft Delete Exclusion
  Sources/FluentBenchmark/Tests/TimestampTests.swift
  Sources/FluentKit/Properties/Timestamp.swift
Labels: bug, semver-patch

#236 Encode @OptionalParent to nil if id is nil
  Sources/FluentKit/Properties/OptionalParent.swift
Labels: bug, semver-patch

#237 Make @Timestamp properties stable again
  Sources/FluentBenchmark/Tests/TimestampTests.swift
  Sources/FluentKit/Properties/Timestamp.swift
Labels: bug, semver-patch

#240 Revert "Encode @OptionalParent to nil if id is nil"
  Sources/FluentKit/Properties/OptionalParent.swift
Labels: enhancement, semver-minor

#241 Test Database Improvements
  Sources/XCTFluent/TestDatabase.swift
  Tests/FluentKitTests/QueryBuilderTests.swift
Labels: enhancement, semver-minor

#246 Made DatabaseSchema.DataType.Enum Initializer Public
  Sources/FluentKit/Schema/DatabaseSchema.swift
Labels: enhancement, semver-minor

#250 Replace Mirror with Azoy/Echo
  Package.swift
  Sources/FluentKit/Model/AnyModel.swift
  Sources/FluentKit/Model/Fields.swift
  Sources/FluentKit/Schema/DatabaseSchema.swift
Labels: enhancement

#248 Query builder timestamps + soft delete
  Sources/FluentBenchmark/Tests/SoftDeleteTests.swift
  Sources/FluentBenchmark/Tests/TimestampTests.swift
  Sources/FluentKit/Model/Model+CRUD.swift
  Sources/FluentKit/Query/Builder/QueryBuilder.swift
Labels: bug, enhancement, semver-minor

#256 Add discardableResult to QueryBuilder.group
  Sources/FluentKit/Query/Builder/QueryBuilder+Group.swift
Labels: enhancement, semver-patch

#258 Fix inverse subset serialization
  Sources/FluentBenchmark/Tests/FilterTests.swift
  Sources/FluentSQL/SQLQueryConverter.swift
Labels: bug, semver-patch
