Repository vapor/fluent-kit, pull requests merged in 2020-05, with the labels that each got.

#262 Publicize NestedProperty and DatabaseOutput utilities
  Sources/FluentKit/Database/DatabaseOutput+Cascade.swift
  Sources/FluentKit/Database/DatabaseOutput+Nested.swift
  Sources/FluentKit/Properties/NestedProperty.swift
Labels: enhancement, semver-minor

#263 Fixes timestamp update when model doesn't have changes
  Sources/FluentBenchmark/Tests/ModelTests.swift
  Sources/FluentBenchmark/Tests/TimestampTests.swift
  Sources/FluentKit/Model/Model+CRUD.swift
Labels: bug, semver-patch

#267 Fix setting nil on @OptionalField
  Sources/FluentBenchmark/Tests/ModelTests.swift
  Sources/FluentBenchmark/Tests/TimestampTests.swift
  Sources/FluentKit/Model/Model+CRUD.swift
  Sources/FluentKit/Properties/OptionalField.swift
Labels: bug, semver-patch

#268 Uniform field paths
  Sources/FluentBenchmark/Tests/GroupTests.swift
  Sources/FluentBenchmark/Tests/TimestampTests.swift
  Sources/FluentKit/Database/DatabaseInput.swift
  Sources/FluentKit/Database/DatabaseOutput+Cascade.swift
  Sources/FluentKit/Database/DatabaseOutput+Nested.swift
  Sources/FluentKit/Database/DatabaseOutput+Prefix.swift
  Sources/FluentKit/Database/DatabaseOutput.swift
  Sources/FluentKit/Database/DummyDatabase.swift
  Sources/FluentKit/Enum/EnumProperty.swift
  Sources/FluentKit/Enum/OptionalEnumProperty.swift
  Sources/FluentKit/Model/AnyModel.swift
  Sources/FluentKit/Model/Fields+Codable.swift
  Sources/FluentKit/Model/Fields.swift
  Sources/FluentKit/Model/Model+CRUD.swift
  Sources/FluentKit/Model/ModelAlias.swift
  Sources/FluentKit/Operators/FieldOperators.swift
  Sources/FluentKit/Operators/ValueOperators+Array.swift
  Sources/FluentKit/Operators/ValueOperators+String.swift
  Sources/FluentKit/Operators/ValueOperators.swift
  Sources/FluentKit/Properties/Children.swift
  Sources/FluentKit/Properties/CompoundField.swift
  Sources/FluentKit/Properties/Field.swift
  Sources/FluentKit/Properties/FieldKey.swift
  Sources/FluentKit/Properties/Group.swift
  Sources/FluentKit/Properties/ID.swift
  Sources/FluentKit/Properties/NestedProperty.swift
  Sources/FluentKit/Properties/OptionalField.swift
  Sources/FluentKit/Properties/OptionalParent.swift
  Sources/FluentKit/Properties/Parent.swift
  Sources/FluentKit/Properties/Property.swift
  Sources/FluentKit/Properties/Siblings.swift
  Sources/FluentKit/Properties/Timestamp.swift
  Sources/FluentKit/Properties/TimestampFormat.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Aggregate.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Filter.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Join.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Set.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Sort.swift
  Sources/FluentKit/Query/Builder/QueryBuilder.swift
  Sources/FluentSQL/SQLQueryConverter.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
  Sources/XCTFluent/TestDatabase.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: enhancement

#192 add Database.inTransaction
  Sources/FluentBenchmark/Tests/TransactionTests.swift
  Sources/FluentKit/Database/Database.swift
Labels: enhancement

#200 Fix dummy db placeholder
  Tests/FluentKitTests/DummyDatabaseForTestSQLSerializer.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: bug

#220 Clear database middleware and run middleware on batch creation
  Sources/FluentBenchmark/Tests/MiddlewareTests.swift
  Sources/FluentKit/Database/Databases.swift
  Sources/FluentKit/Model/Model+CRUD.swift
Labels: enhancement

#265 Add entire models to the test database output.
  Sources/FluentBenchmark/SolarSystem/Planet.swift
  Sources/XCTFluent/TestDatabase.swift
  Tests/FluentKitTests/QueryBuilderTests.swift
Labels: enhancement

#271 Track Migrations Per Database
  Package.swift
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/SolarSystem/SolarSystem.swift
  Sources/FluentBenchmark/Tests/MigratorTests.swift
  Sources/FluentKit/Database/Databases.swift
  Sources/FluentKit/Migration/Migrations.swift
  Sources/FluentKit/Migration/Migrator.swift
  Sources/FluentKit/Query/Builder/QueryBuilder.swift
Labels: bug, semver-minor

#275 Make siblings relation properties public
  Sources/FluentKit/Properties/Siblings.swift
Labels: enhancement

#290 Additional fixes for #278 (problematic usage of XCTUnwrap)
  Sources/FluentBenchmark/Tests/MigratorTests.swift
  Sources/FluentBenchmark/Tests/TimestampTests.swift
Labels: bug

#291 CI: Test all the drivers on all the Swift images at once
  .github/workflows/test.yml
Labels: enhancement

#304 Add helper methods for adding multiple Migrations at once
  Sources/FluentBenchmark/Tests/MigratorTests.swift
  Sources/FluentKit/Migration/Migrations.swift
Labels: enhancement, semver-minor
