Repository vapor/fluent-kit, pull requests merged in 2020-03, with the labels that each got.

#190 Make MigrationLog's name unique
  Sources/FluentKit/Migration/MigrationLog.swift
Labels: bug, semver-patch

#191 Siblings detach array support
  Sources/FluentBenchmark/Tests/SiblingsTests.swift
  Sources/FluentKit/Properties/Siblings.swift
Labels: enhancement, semver-minor

#182 Improve invalid @Field access fatalError
  Sources/FluentKit/Properties/Field.swift
Labels: enhancement, semver-patch

#110 Add XCTFluent module with TestDatabase
  Package.swift
  Sources/XCTFluent/TestDatabase.swift
  Tests/FluentKitTests/DummyDatabaseForTestSQLSerializer.swift
  Tests/FluentKitTests/QueryBuilderTests.swift
Labels: enhancement, semver-minor

#193 Pass join method parameter
  Sources/FluentKit/Query/Builder/QueryBuilder+Join.swift
Labels: bug, semver-patch

#195 Omit empty filter groups from query
  Sources/FluentBenchmark/Tests/FilterTests.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Group.swift
Labels: bug, semver-patch

#125 Ensure createdAt/updatedAt timestamps equal on creation
  Sources/FluentKit/Model/Model+CRUD.swift
Labels: enhancement

#197 Batch update timestamps at the same time
  Sources/FluentKit/Model/Model+CRUD.swift
Labels: enhancement, semver-patch

#198 Fix @Enum codable serialization
  Sources/FluentKit/Properties/Field.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: bug, semver-patch

#209 Handle .bind EnumProperty
  Sources/FluentKit/Enum/EnumProperty.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: bug, semver-patch

#213 Add ability to specify `IF NOT EXISTS` for schema create actions
  Sources/FluentKit/Migration/MigrationLog.swift
  Sources/FluentKit/Migration/Migrator.swift
  Sources/FluentKit/Schema/DatabaseSchema.swift
  Sources/FluentKit/Schema/SchemaBuilder.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: enhancement, semver-minor

#214 Brute-force past a weird SPM issue in the Mongo test workflow
  .github/workflows/test.yml
Labels: bug

#203 Provide custom value operator handling for enum
  Sources/FluentBenchmark/Tests/EnumTests.swift
  Sources/FluentKit/Enum/EnumProperty.swift
  Sources/FluentKit/Operators/ValueOperators+Array.swift
  Sources/FluentKit/Operators/ValueOperators+String.swift
  Sources/FluentKit/Operators/ValueOperators.swift
  Sources/FluentKit/Properties/Property.swift
  Tests/FluentKitTests/FilterQueryTests.swift
Labels: bug, semver-minor

#217 Add an @OptionalEnum property wrapper
  Sources/FluentBenchmark/Tests/EnumTests.swift
  Sources/FluentKit/Enum/OptionalEnumProperty.swift
  Sources/FluentKit/Properties/OptionalField.swift
Labels: enhancement, semver-minor

#221 Custom Timestamp Formats
  Sources/FluentBenchmark/Tests/TimestampTests.swift
  Sources/FluentKit/Properties/Timestamp.swift
Labels: enhancement, semver-minor
