Repository vapor/fluent-kit, pull requests merged in 2021-11, with the labels that each got.

#455 optional query tests
  .github/workflows/test.yml
  Tests/FluentKitTests/OptionalEnumQueryTests.swift
  Tests/FluentKitTests/OptionalFieldQueryTests.swift
  Tests/FluentKitTests/TestUtilities.swift
Labels: enhancement, no-release-needed

#470 Fix `AsyncModelMiddleware`
  .github/workflows/test.yml
  Sources/FluentBenchmark/Tests/MiddlewareTests.swift
  Sources/FluentBenchmark/Tests/UniqueTests.swift
  Sources/FluentKit/Concurrency/AsyncModelMiddleware.swift
  Sources/FluentKit/Concurrency/ModelResponder+Concurrency.swift
  Sources/FluentKit/Model/Model+CRUD.swift
Labels: semver-patch

#440 Remove `Codable` restriction on `Page.map`
  Sources/FluentKit/Query/Builder/QueryBuilder+Paginate.swift
Labels: enhancement, semver-patch

#471 Add missing Concurrency-based versions of the SQLQueryFetcher extensions
  Sources/FluentSQL/SQLDatabase+Model+Concurrency.swift
  Sources/FluentSQL/SQLDatabase+Model.swift
Labels: enhancement, semver-minor
