Repository vapor/fluent-kit, pull requests merged in 2022-04, with the labels that each got.

#498 Further improve the workaround for Mirror's slowness
  .github/workflows/test.yml
  Sources/FluentKit/Model/AnyModel.swift
  Sources/FluentKit/Model/Fields.swift
  Sources/FluentKit/Model/MirrorBypass.swift
  Tests/FluentKitTests/AsyncTests/AsyncFilterQueryTests.swift
  Tests/FluentKitTests/AsyncTests/AsyncFluentKitTests.swift
  Tests/FluentKitTests/AsyncTests/AsyncQueryBuilderTests.swift
  Tests/FluentKitTests/DummyDatabaseForTestSQLSerializer.swift
  Tests/FluentKitTests/FilterQueryTests.swift
  Tests/FluentKitTests/FluentKitTests.swift
  Tests/FluentKitTests/OptionalEnumQueryTests.swift
  Tests/FluentKitTests/OptionalFieldQueryTests.swift
  Tests/FluentKitTests/QueryBuilderTests.swift
Labels: enhancement, semver-patch

#499 Fix input handling for `EnumProperty` and `OptionalEnumProperty`
  Sources/FluentBenchmark/Tests/EnumTests.swift
  Sources/FluentKit/Enum/EnumProperty.swift
  Sources/FluentKit/Enum/OptionalEnumProperty.swift
Labels: bug, semver-patch

#501 Make accessing `model.id` safe
  Sources/FluentKit/Model/Model+CRUD.swift
  Sources/FluentKit/Properties/Siblings.swift
Labels: semver-patch
