Repository vapor/fluent-kit, pull requests merged in 2022-06, with the labels that each got.

#510 Allow public use of `TimestampFormatFactory.makeFormat()`
  Sources/FluentKit/Properties/TimestampFormat.swift
  Sources/FluentSQL/SQLQueryConverter.swift
Labels: enhancement, semver-minor

#476 Allow sorting by `@Group` field properties
  Sources/FluentKit/Query/Builder/QueryBuilder+Sort.swift
  Tests/FluentKitTests/AsyncTests/AsyncFluentKitTests.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: semver-patch

#509 Initial support for composite primary keys
  .github/workflows/main-codecov.yml
  .github/workflows/test.yml
  README.md
  Sources/FluentBenchmark/FluentBenchmarker.swift
  Sources/FluentBenchmark/SolarSystem/GalacticJurisdiction.swift
  Sources/FluentBenchmark/SolarSystem/Galaxy.swift
  Sources/FluentBenchmark/SolarSystem/Jurisdiction.swift
  Sources/FluentBenchmark/Tests/CompositeIDTests.swift
  Sources/FluentKit/Concurrency/QueryBuilder+Concurrency.swift
  Sources/FluentKit/Enum/EnumProperty.swift
  Sources/FluentKit/Enum/OptionalEnumProperty.swift
  Sources/FluentKit/Model/AnyModel.swift
  Sources/FluentKit/Model/Model+CRUD.swift
  Sources/FluentKit/Model/Model.swift
  Sources/FluentKit/Model/ModelAlias.swift
  Sources/FluentKit/Properties/CompositeID.swift
  Sources/FluentKit/Properties/Field.swift
  Sources/FluentKit/Properties/Group.swift
  Sources/FluentKit/Properties/ID.swift
  Sources/FluentKit/Properties/OptionalField.swift
  Sources/FluentKit/Properties/OptionalParent.swift
  Sources/FluentKit/Properties/Parent.swift
  Sources/FluentKit/Properties/Property.swift
  Sources/FluentKit/Properties/Timestamp.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Aggregate.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Filter.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Set.swift
  Sources/FluentKit/Query/Builder/QueryBuilder.swift
  Sources/FluentKit/Schema/DatabaseSchema.swift
  Sources/FluentKit/Schema/SchemaBuilder.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
  Tests/FluentKitTests/AsyncTests/AsyncFilterQueryTests.swift
  Tests/FluentKitTests/AsyncTests/AsyncFluentKitTests.swift
  Tests/FluentKitTests/AsyncTests/AsyncQueryBuilderTests.swift
  Tests/FluentKitTests/CompositeIDTests.swift
  Tests/FluentKitTests/FilterQueryTests.swift
  Tests/FluentKitTests/FluentKitTests.swift
  Tests/FluentKitTests/OptionalEnumQueryTests.swift
  Tests/FluentKitTests/OptionalFieldQueryTests.swift
  Tests/FluentKitTests/QueryBuilderTests.swift
  Tests/FluentKitTests/TestUtilities.swift
Labels: enhancement, semver-minor

#511 Make the `$id.exists` flag on models more generically available
  Sources/FluentKit/Model/Model+CRUD.swift
  Sources/FluentKit/Model/Model.swift
Labels: enhancement, semver-minor

#514 Add missing info to missingParent error, fix ID compare for composite IDs
  Sources/FluentBenchmark/Tests/SoftDeleteTests.swift
  Sources/FluentKit/FluentError.swift
  Sources/FluentKit/Operators/ValueOperators.swift
  Sources/FluentKit/Properties/Parent.swift
  Tests/FluentKitTests/CompositeIDTests.swift
Labels: bug, enhancement, semver-minor

#515 Enable MirrorBypass in Swift 5.7
  Sources/FluentKit/Model/MirrorBypass.swift
Labels: enhancement, semver-patch

#516 Explicitly forbid unsupported combinations of @CompositeID with @Parent etc.
  Sources/FluentKit/Properties/Children.swift
  Sources/FluentKit/Properties/OptionalChild.swift
  Sources/FluentKit/Properties/OptionalParent.swift
  Sources/FluentKit/Properties/Parent.swift
  Sources/FluentKit/Properties/Siblings.swift
Labels: bug, semver-patch

#519 Additional API for pagination to access individual page
  Sources/FluentKit/Concurrency/QueryBuilder+Concurrency.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Paginate.swift
  Tests/FluentKitTests/AsyncTests/AsyncQueryBuilderTests.swift
Labels: semver-minor

#520 Add ability to control transactions
  Sources/FluentKit/Database/TransactionControlDatabase.swift
Labels: semver-minor
