Repository vapor/fluent-kit, pull requests merged in 2022-07, with the labels that each got.

#521 Formatted boolean properties
  Sources/FluentBenchmark/Tests/EnumTests.swift
  Sources/FluentKit/Properties/Boolean.swift
  Sources/FluentKit/Properties/BooleanPropertyFormat.swift
  Sources/FluentKit/Properties/OptionalBoolean.swift
Labels: enhancement, semver-minor

#522 Make it possible to drop foreign key constraints with MySQL 5.7
  Sources/FluentBenchmark/Tests/SchemaTests.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
Labels: bug, semver-minor

#524 Add experimental watchOS support
  Package.swift
Labels: semver-patch

#526 Log start and finish of migration prepares and reverts
  .github/workflows/main-codecov.yml
  .github/workflows/test.yml
  Sources/FluentKit/Migration/Migrator.swift
  Sources/FluentKit/Properties/Property.swift
Labels: enhancement, semver-patch
