Repository vapor/fluent-kit, pull requests merged in 2022-03, with the labels that each got.

#416 Add test for adding multiple enum cases at once
  Sources/FluentBenchmark/Tests/EnumTests.swift
Labels: no-release-needed

#485 Adds a page count to `PageMetadata`
  Sources/FluentBenchmark/Tests/PaginationTests.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Paginate.swift
Labels: semver-minor

#493 Address performance regression in Swift 5.6
  Sources/FluentKit/Model/Fields.swift
Labels: bug, semver-patch

#494 Enable looking up database names of multiple model key paths at once
  Sources/FluentKit/Model/Fields.swift
Labels: enhancement, semver-patch
