Repository vapor/fluent-kit, pull requests merged in 2023-02, with the labels that each got.

#547 Complex join conditions and composite-key parent relations
  .github/workflows/test.yml
  Package.swift
  Sources/FluentBenchmark/Tests/CompositeIDTests.swift
  Sources/FluentBenchmark/Tests/CompositeParentTests.swift
  Sources/FluentBenchmark/Tests/FilterTests.swift
  Sources/FluentBenchmark/Tests/JoinTests.swift
  Sources/FluentKit/Database/DatabaseInput.swift
  Sources/FluentKit/Database/DatabaseOutput+Cascade.swift
  Sources/FluentKit/Database/DatabaseOutput+Prefix.swift
  Sources/FluentKit/Database/DatabaseOutput.swift
  Sources/FluentKit/Database/KeyPrefixingStrategy.swift
  Sources/FluentKit/FluentError.swift
  Sources/FluentKit/Model/AnyModel.swift
  Sources/FluentKit/Model/Fields+Codable.swift
  Sources/FluentKit/Model/Fields.swift
  Sources/FluentKit/Model/ModelAlias.swift
  Sources/FluentKit/Model/Schema.swift
  Sources/FluentKit/Operators/FieldOperators.swift
  Sources/FluentKit/Operators/ValueOperators.swift
  Sources/FluentKit/Properties/CompositeParent.swift
  Sources/FluentKit/Properties/OptionalParent.swift
  Sources/FluentKit/Properties/Parent.swift
  Sources/FluentKit/Properties/Property.swift
  Sources/FluentKit/Properties/Relation.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Aggregate.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Filter.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Join+DirectRelations.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Join.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Sort.swift
  Sources/FluentKit/Query/Builder/QueryBuilder.swift
  Sources/FluentKit/Query/Database/DatabaseQuery+Filter.swift
  Sources/FluentKit/Query/Database/DatabaseQuery+Join.swift
  Sources/FluentKit/Utilities/SomeCodingKey.swift
  Sources/FluentSQL/Exports.swift
  Sources/FluentSQL/SQLList+Deprecated.swift
  Sources/FluentSQL/SQLQueryConverter.swift
  Tests/FluentKitTests/AsyncTests/AsyncFilterQueryTests.swift
  Tests/FluentKitTests/AsyncTests/AsyncFluentKitTests.swift
  Tests/FluentKitTests/FilterQueryTests.swift
  Tests/FluentKitTests/FluentKitTests.swift
Labels: enhancement, semver-minor

#549 Add ability to control migration log level
  Sources/FluentKit/Migration/Migrator.swift
Labels: semver-minor

#550 Additional relations support for CompositeID models
  .github/workflows/test.yml
  Package.swift
  Sources/FluentBenchmark/Tests/CompositeIDTests.swift
  Sources/FluentBenchmark/Tests/CompositeParentTests.swift
  Sources/FluentBenchmark/Tests/CompositeRelationTests.swift
  Sources/FluentKit/Concurrency/AsyncMigration.swift
  Sources/FluentKit/Concurrency/AsyncModelMiddleware.swift
  Sources/FluentKit/Concurrency/Children+Concurrency.swift
  Sources/FluentKit/Concurrency/Database+Concurrency.swift
  Sources/FluentKit/Concurrency/EnumBuilder+Concurrency.swift
  Sources/FluentKit/Concurrency/Model+Concurrency.swift
  Sources/FluentKit/Concurrency/ModelResponder+Concurrency.swift
  Sources/FluentKit/Concurrency/OptionalChild+Concurrency.swift
  Sources/FluentKit/Concurrency/OptionalParent+Concurrency.swift
  Sources/FluentKit/Concurrency/Parent+Concurrency.swift
  Sources/FluentKit/Concurrency/QueryBuilder+Concurrency.swift
  Sources/FluentKit/Concurrency/Relation+Concurrency.swift
  Sources/FluentKit/Concurrency/SchemaBuilder+Concurrency.swift
  Sources/FluentKit/Concurrency/Siblings+Concurrency.swift
  Sources/FluentKit/Database/DatabaseInput.swift
  Sources/FluentKit/Database/KeyPrefixingStrategy.swift
  Sources/FluentKit/Enum/EnumProperty.swift
  Sources/FluentKit/Enum/OptionalEnumProperty.swift
  Sources/FluentKit/FluentError.swift
  Sources/FluentKit/Model/AnyModel.swift
  Sources/FluentKit/Model/Fields.swift
  Sources/FluentKit/Properties/Children.swift
  Sources/FluentKit/Properties/CompositeChildren.swift
  Sources/FluentKit/Properties/CompositeID.swift
  Sources/FluentKit/Properties/CompositeOptionalChild.swift
  Sources/FluentKit/Properties/CompositeOptionalParent.swift
  Sources/FluentKit/Properties/CompositeParent.swift
  Sources/FluentKit/Properties/Field.swift
  Sources/FluentKit/Properties/Group.swift
  Sources/FluentKit/Properties/OptionalChild.swift
  Sources/FluentKit/Properties/OptionalField.swift
  Sources/FluentKit/Properties/Property.swift
  Sources/FluentKit/Properties/Relation.swift
  Tests/FluentKitTests/AsyncTests/AsyncFilterQueryTests.swift
  Tests/FluentKitTests/AsyncTests/AsyncFluentKitTests.swift
  Tests/FluentKitTests/AsyncTests/AsyncQueryBuilderTests.swift
  Tests/FluentKitTests/CompositeIDTests.swift
  Tests/FluentKitTests/FluentKitTests.swift
  Tests/FluentKitTests/QueryBuilderTests.swift
Labels: bug, enhancement, semver-minor

#553 Remove limitations on nested relations in CompositeIDs
  .github/workflows/test.yml
  Sources/FluentBenchmark/Tests/CompositeRelationTests.swift
  Sources/FluentKit/Database/DatabaseInput.swift
  Sources/FluentKit/Operators/ValueOperators.swift
  Sources/FluentKit/Properties/Children.swift
  Sources/FluentKit/Properties/CompositeID.swift
  Sources/FluentKit/Properties/OptionalChild.swift
  Sources/FluentKit/Properties/OptionalParent.swift
  Sources/FluentKit/Properties/Parent.swift
  Sources/FluentKit/Properties/Siblings.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Aggregate.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Filter.swift
Labels: semver-patch
