Repository vapor/fluent-kit, pull requests merged in 2023-07, with the labels that each got.

#572 Leverage the new support for nested path expressions in SQLKit
  .github/CODEOWNERS
  .github/CONTRIBUTING.md
  Package.swift
  README.md
  Sources/FluentSQL/SQLJSONColumnPath.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
Labels: semver-minor

#569 Handle aggregate types a very tiny bit better
  Sources/FluentKit/Query/Builder/QueryBuilder+Aggregate.swift
Labels: bug, semver-patch

#574 Add possibility of nested eager load builder to throw
  Sources/FluentKit/Query/Builder/QueryBuilder+EagerLoad.swift
Labels: semver-patch

#575 Fully work around MySQL 5.7's lack of the DROP CONSTRAINT statement
  .github/workflows/api-docs.yml
  .github/workflows/test.yml
  Sources/FluentBenchmark/Tests/SchemaTests.swift
  Sources/FluentKit/Schema/DatabaseSchema.swift
  Sources/FluentKit/Schema/SchemaBuilder.swift
  Sources/FluentSQL/SQLSchemaConverter.swift
Labels: bug, semver-minor
