Repository vapor/fluent-kit, pull requests merged in 2025-01, with the labels that each got.

#624 Fix Fluent model encoding for SQLKit and several Sendable warnings
  Package.swift
  Package@swift-5.9.swift
  Sources/FluentKit/Concurrency/Database+Concurrency.swift
  Sources/FluentKit/Model/Fields+Codable.swift
  Sources/FluentKit/Properties/Relation.swift
  Sources/FluentKit/Query/Builder/QueryBuilder+Paginate.swift
  Sources/FluentSQL/SQLDatabase+Model.swift
  Tests/FluentKitTests/DummyDatabaseForTestSQLSerializer.swift
  Tests/FluentKitTests/FluentKitTests.swift
  Tests/FluentKitTests/SQLTests.swift
Labels: semver-minor

#626 Be more specific about which model's ID property is missing in error message
  Sources/FluentKit/Model/AnyModel.swift
Labels: semver-patch

#627 Add missing targets to api-docs.yml
  .github/workflows/api-docs.yml
Labels: no-release-needed
